# Generated by Django 4.2.11 on 2024-09-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Disponível'), (2, 'Indisponível'), (3, 'Em Manutenção')], default=1)),
            ],
        ),
    ]
