# Generated by Django 5.1 on 2024-09-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Disponível'), (2, 'Emprestado'), (3, 'Em Manutenção')], default=1),
        ),
    ]
