# Generated by Django 5.1 on 2024-08-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.IntegerField(choices=[(1, 'Funcionario'), (2, 'Estagiario'), (3, 'Outro')], default=3),
        ),
    ]
