# Generated by Django 5.1 on 2024-09-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.IntegerField(choices=[(1, 'Root'), (2, 'Funcionario'), (3, 'Estagiario'), (4, 'Outro')], default=4),
        ),
    ]
