# Generated by Django 5.1 on 2024-09-03 12:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamento', '0002_alter_equipamento_status'),
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('dataInicio', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('dataConclusao', models.DateTimeField(blank=True, null=True)),
                ('manutentor', models.CharField(max_length=100)),
                ('observacoesDeConclusao', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Concluído'), (2, 'Em Andamento'), (3, 'Incompleto')], default=2)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamento.equipamento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionario.funcionario')),
            ],
        ),
    ]
