# Generated by Django 5.1 on 2024-09-03 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='dataConclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='dataInicio',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
