# Generated by Django 5.1 on 2024-09-01 23:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisitante', models.CharField(max_length=50)),
                ('tipoDoRequisitante', models.IntegerField(choices=[(1, 'Aluno'), (2, 'Professor'), (3, 'Funcionário'), (4, 'Outro')], default=4)),
                ('sala', models.IntegerField()),
                ('curso', models.CharField(max_length=20)),
                ('semestre', models.IntegerField()),
                ('dataEmprestimo', models.DateField(default=django.utils.timezone.now)),
                ('dataDevolucao', models.DateField(blank=True, null=True)),
                ('observacoesDeDevolucao', models.CharField(blank=True, max_length=255)),
                ('status', models.IntegerField(choices=[(1, 'Devolvido'), (2, 'Em Andamento'), (3, 'Atrasado')], default=2)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionario.funcionario')),
            ],
        ),
    ]
