# Generated by Django 5.1 on 2024-09-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestamista', models.CharField(max_length=50)),
                ('tipoDoPrestamista', models.IntegerField(choices=[(1, 'Aluno'), (2, 'Professor'), (3, 'Funcionário'), (4, 'Outro')], default=4)),
                ('sala', models.IntegerField()),
                ('curso', models.CharField(max_length=20)),
                ('semestre', models.IntegerField()),
                ('dataEmprestimo', models.DateTimeField()),
                ('dataDevolucao', models.DateTimeField(blank=True, null=True)),
                ('observacoesDeDevolucao', models.CharField(blank=True, max_length=255)),
                ('status', models.IntegerField(choices=[(1, 'Devolvido'), (2, 'Em Andamento'), (3, 'Atrasado')], default=2)),
            ],
        ),
    ]
