# Generated by Django 5.1 on 2024-09-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0003_alter_emprestimo_semestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='semestre',
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='sala',
            field=models.CharField(max_length=50),
        ),
    ]
