# Generated by Django 5.1 on 2024-09-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0004_remove_emprestimo_semestre_alter_emprestimo_sala'),
        ('equipamento', '0001_initial'),
        ('itemEmprestimo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='equipamentos',
            field=models.ManyToManyField(through='itemEmprestimo.ItemEmprestimo', to='equipamento.equipamento'),
        ),
    ]
