# Generated by Django 5.1 on 2024-09-02 23:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0005_emprestimo_equipamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='dataEmprestimo',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
