# Generated by Django 5.1 on 2024-09-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0006_alter_emprestimo_dataemprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='dataEmprestimo',
            field=models.DateField(blank=True),
        ),
    ]
