# Generated by Django 5.1 on 2024-09-03 18:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0008_alter_emprestimo_dataemprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='dataEmprestimo',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
