# Generated by Django 5.1 on 2024-09-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0009_alter_emprestimo_dataemprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='curso',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
